name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx (optional but recommended)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to Docker Hub (optional, if you want to push)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build the Docker image
      - name: Build Docker image
        run: |
          IMAGE_TAG=my-image-name:$(date +%s)
          docker build -f Dockerfile -t $IMAGE_TAG .

      # 5. (Optional) Push to Docker Hub
      - name: Push Docker image
        run: |
          IMAGE_TAG=my-image-name:$(date +%s)
          docker push $IMAGE_TAG
