name: Docker Compose CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

     # 4. Build all Docker images using docker-compose
      - name: Build Docker images
        run: |
          IMAGE_TAG=my-image-name:$(date +%s)
          docker build -f ./Dockerfile -t $IMAGE_TAG .
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        shell: /usr/bin/bash -e {0}
        working-directory: ${{ github.workspace }}
      # 5. Push all Docker images using docker-compose
      - name: Push Docker images
        run: docker-compose -f docker-compose.prod.yml push
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
