name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build and tag Docker image
      - name: Build Docker image
        run: |
          IMAGE_TAG=bhanux100/server-webrtc-chat:latest
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -f omegle/server/Dockerfile -t $IMAGE_TAG omegle/server

      # 5. Push Docker image
      - name: Push Docker image
        run: docker push $IMAGE_TAG
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
