name: Docker Compose CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build all Docker images using docker-compose
      # 4. Build all Docker images using docker-compose
      - name: Build Docker image
        run: |
          IMAGE_TAG=my-image-name:$(date +%s)
          docker build -f server/Dockerfile -t $IMAGE_TAG .
          
      - name: Push Docker image
        run: docker push $IMAGE_TAG
